version: '3'
services:
  sftp:
    build: .
    volumes:
      - /mnt/volume/config/users.conf:/etc/sftp/users.conf:ro
      - /mnt/volume/config/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - /mnt/volume/config/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./startup-scripts/:/etc/sftp.d
      - /mnt/volume/home:/home
    ports:
      - "2222:22"
